### ISSUE TITLE
Remember last loaded file

### ISSUE THREAD

**Issue by teresaejunior** [poleguy/cherrybud#2]
A follow-up to https://github.com/giuspen/cherrytree/issues/328#issuecomment-734804815 - Cherrybud won't remember the last loaded file.

**Comment by poleguy** [comment]
> Just a heads up, this is something I had noticed years ago: ctd files use a lot more RAM than ctb in CherryTree. 3.5 times more in a test I just did.

That's on the todo list. It also has to not crash on large files... see issue #1 

> I loaded the ctd in Cherrybud and it loaded fine. All formatting is removed from the text, including hyperlinks, and a weird amount of newlines get inserted instead. But I hadn't problems viewing any nodes or subnodes, which I have thousands, but all in RTF/source code (no attachments).

Yes, I'll attend to that. The formatting is minimal to prove that I can read it for now.  Everything is treated as strings and pictuers are skipped. The extra newlines are inserted because I don't filter anything out of the xml, and the newlines are in the xml. This is easy to fix by filtering for <rich_text>, etc.. Will do.

Thanks for testing it out. Primarily I'm looking for major foundational flaws (crashes, won't load at all, device incompatible, etc.) at this point. It's very early on.

**Comment by poleguy** [comment]
A new APK is up that should remember the last loaded file.
It's a baby step in hopefully the right direction.
Again, it's a work in progress and not done.
 
http:/poleguy.com/cherrybud_v1.1.apk

(I also have successfully published the old version up on Google Play, although the price is _very_ high and it's not the latest code).

**Comment by teresaejunior** [comment]
It works, thanks! This makes Cherrybud already usable as read-only.
